--Min/Max Value
MIN_ID		=1000		--4 digit, by DataManager::GetDesc()
MAX_ID		=268435455	--9 digit, by DataManager::GetDesc()
MAX_COUNTER	=65535		--max number for adding/removing counters, by card::add_counter(), field::remove_counter()
MAX_NUMBER	=999999999	--Max number allowed in YGOPro
--Card ID
CARD_KING_TRITONUS				=10007112	--"Mark of Tritonus" (7CLA 24/110)
CARD_INFERNUS_THE_IMMOLATOR		=10007114	--"Mark of Infernus" (7CLA 53/110)
CARD_ETERNAL_HAVEN				=10009081	--"Mark of Eternal Haven" (9SHA 4/80)
CARD_QUEEN_KALIMA				=10009083	--"Mark of Kalima" (9SHA 23/80)
CARD_ALMIGHTY_COLOSSUS			=10010085	--"Mark of Almighty Colossus" (10INV S5/S10)
CARD_IGNISS						=10015101	--"Raptor-Ace Valko" (15VTX 112/160)
CARD_ICE_BLADE					=10001005	--EVENT_CUSTOM+EVENT_TRIGGER_SHIELD_BLAST
CARD_SKEETER_SWARMER			=10001019	--EVENT_CUSTOM+EVENT_WIN_BATTLE
CARD_STAR_LANTERN				=10002009	--EVENT_CUSTOM+EVENT_BLOCK
CARD_BOTTLE_OF_WISHES			=10006012	--EVENT_CUSTOM+EVENT_CAST_FREE
CARD_KING_POSEIDON				=10007023	--EVENT_CUSTOM+EVENT_LOSE_BATTLE
CARD_KHORDIA_SOUL_TYRANT		=10009090	--EVENT_CUSTOM+EVENT_EVOLUTION_TO_BZONE
CARD_VECTRON_CRAWLER			=10012054	--EVENT_CUSTOM+EVENT_BECOME_BLOCKED
CARD_SPARK_OF_HUNGER			=10016011	--EVENT_CUSTOM+EVENT_CLASH
--Location
LOCATION_ALL		=0xff		--All locations
LOCATION_DECK		=0x01		--Deck
LOCATION_HAND		=0x02		--Hand
LOCATION_BZONE		=0x04		--Battle Zone
LOCATION_SZONE		=0x08		--Shield Zone (sequences 0~4)
LOCATION_MZONEUNT	=0x10		--Mana Zone (untapped cards)
LOCATION_MZONETAP	=0x20		--Mana Zone (tapped cards)
LOCATION_DPILE		=0x20		--Discard Pile
LOCATION_MZONE		=0x30		--Mana Zone
LOCATION_EXTRA		=0x40		--(unused)
LOCATION_ESOURCE	=0x80		--Evolution Source
--Location (for redirect)
--If you specify LOCATION_DECK in the redirection effect, the card will return to the top of the deck
LOCATION_DECKBOT	=0x10001	--Bottom of the Deck
LOCATION_DECKSHF	=0x20001	--(unused)
--Deck Sequence (for Duel.SendtoDeck)
SEQ_DECK_TOP		=0		--Return to the top of the deck
SEQ_DECK_BOTTOM		=1		--Return to the bottom of the deck
SEQ_DECK_SHUFFLE	=2		--Shuffle into the deck
SEQ_DECK_UNEXIST	=-2		--Disappear from the game
--Zone Sequence (for Card.GetSequence, Card.GetPreviousSequence, etc.)
SEQ_MZONE_LEFT		=0		--(reserved) Leftmost Main Monster Zone
SEQ_MZONE_MID_LEFT	=1		--(reserved) Center-left Main Monster Zone
SEQ_MZONE_MID		=2		--(reserved) Center Main Monster Zone
SEQ_MZONE_MID_RIGHT	=3		--(reserved) Center-right Main Monster Zone
SEQ_MZONE_RIGHT		=4		--(reserved) Rightmost Main Monster Zone
SEQ_MZONE_EX_LEFT	=5		--(reserved) Extra Monster Zone
SEQ_SZONE_LEFT		=0		--(reserved) Leftmost Spell & Trap Zone
SEQ_SZONE_MID_LEFT	=1		--(reserved) Center-left Spell & Trap Zone
SEQ_SZONE_MID		=2		--(reserved) Center Spell & Trap Zone
SEQ_SZONE_MID_RIGHT	=3		--(reserved) Center-right Spell & Trap Zone
SEQ_SZONE_RIGHT		=4		--(reserved) Rightmost Spell & Trap Zone
SEQ_FZONE			=5		--(reserved) Field Zone
--Zone (Location + Sequence, can be used for EFFECT_DISABLE_FIELD)
ZONE_MZONE				=0x7f		--zone=ZONE_MZONE in Duel.SpecialSummon(targets, sumtype, sumplayer, target_player, nocheck, nolimit, pos, zone)
--Position
POS_FACEUP_UNTAPPED		=0x1	--Face-up untapped
POS_FACEDOWN_UNTAPPED	=0x2	--(unused) Face-down untapped
POS_FACEUP_TAPPED		=0x4	--Face-up tapped
POS_FACEDOWN_TAPPED		=0x8	--(unused) Face-down tapped
POS_FACEUP				=0x5	--Face-up
POS_FACEDOWN			=0xa	--Face-down
POS_UNTAPPED			=0x3	--(unused) Untapped
POS_TAPPED				=0xc	--(unused) Tapped
--Card Type
TYPE_MONSTER		=0x1		--(unused)
TYPE_SPELL			=0x2		--Spell
TYPE_TRAP			=0x4		--(unused)
TYPE_NORMAL			=0x10		--(unused)
TYPE_CREATURE		=0x20		--Creature
TYPE_FUSION			=0x40		--(unused)
TYPE_RITUAL			=0x80		--(unused)
TYPE_TRAPMONSTER	=0x100		--(unused)
TYPE_SPIRIT			=0x200		--(unused)
TYPE_UNION			=0x400		--(unused)
TYPE_MULTICOLORED	=0x800		--Card that has 2 or more civilizations
TYPE_NO_ABILITY		=0x1000		--Creature that has no abilities
TYPE_SYNCHRO		=0x2000		--(unused)
TYPE_TOKEN			=0x4000		--(unused)
TYPE_QUICKPLAY		=0x10000	--(unused)
TYPE_CONTINUOUS		=0x20000	--(unused)
TYPE_EQUIP			=0x40000	--(unused)
TYPE_FIELD			=0x80000	--(unused)
TYPE_COUNTER		=0x100000	--(unused)
TYPE_FLIP			=0x200000	--(unused)
TYPE_TOON			=0x400000	--(unused)
TYPE_XYZ			=0x800000	--(unused)
TYPE_PENDULUM		=0x1000000	--(unused)
TYPE_EVOLUTION		=0x2000000	--Evolution creature
TYPE_LINK			=0x4000000	--(unused)
--Civilization
CIVILIZATION_NONE		=0x0	--No civilization (including Zero and Jokers)
CIVILIZATION_ALL		=0x1f	--All civilizations
CIVILIZATION_LIGHT		=0x01	--Light
CIVILIZATION_WATER		=0x02	--Water
CIVILIZATION_DARKNESS	=0x04	--Darkness
CIVILIZATION_FIRE		=0x08	--Fire
CIVILIZATION_NATURE		=0x10	--Nature
CIVILIZATION_COUNT		=5		--Number of different civilizations
--2 color civilization combinations
CIVILIZATIONS_LW		=0x03	--CIVILIZATION_LIGHT+CIVILIZATION_WATER
CIVILIZATIONS_LD		=0x05	--CIVILIZATION_LIGHT+CIVILIZATION_DARKNESS
CIVILIZATIONS_WD		=0x06	--CIVILIZATION_WATER+CIVILIZATION_DARKNESS
CIVILIZATIONS_LF		=0x09	--CIVILIZATION_LIGHT+CIVILIZATION_FIRE
CIVILIZATIONS_WF		=0x0a	--CIVILIZATION_WATER+CIVILIZATION_FIRE
CIVILIZATIONS_DF		=0x0c	--CIVILIZATION_DARKNESS+CIVILIZATION_FIRE
CIVILIZATIONS_LN		=0x11	--CIVILIZATION_LIGHT+CIVILIZATION_NATURE
CIVILIZATIONS_WN		=0x12	--CIVILIZATION_WATER+CIVILIZATION_NATURE
CIVILIZATIONS_DN		=0x14	--CIVILIZATION_DARKNESS+CIVILIZATION_NATURE
CIVILIZATIONS_FN		=0x18	--CIVILIZATION_FIRE+CIVILIZATION_NATURE
--3 color civilization combinations
CIVILIZATIONS_LWD		=0x07	--CIVILIZATIONS_LW+CIVILIZATION_DARKNESS
CIVILIZATIONS_LWF		=0x0b	--CIVILIZATIONS_LW+CIVILIZATION_FIRE
CIVILIZATIONS_LDF		=0x0d	--CIVILIZATIONS_LD+CIVILIZATION_FIRE
CIVILIZATIONS_WDF		=0x0e	--CIVILIZATIONS_WD+CIVILIZATION_FIRE
CIVILIZATIONS_LWN		=0x13	--CIVILIZATIONS_LW+CIVILIZATION_NATURE
CIVILIZATIONS_LDN		=0x15	--CIVILIZATIONS_LD+CIVILIZATION_NATURE
CIVILIZATIONS_WDN		=0x16	--CIVILIZATIONS_WD+CIVILIZATION_NATURE
CIVILIZATIONS_LFN		=0x19	--CIVILIZATIONS_LF+CIVILIZATION_NATURE
CIVILIZATIONS_WFN		=0x1a	--CIVILIZATIONS_WF+CIVILIZATION_NATURE
CIVILIZATIONS_DFN		=0x1c	--CIVILIZATIONS_DF+CIVILIZATION_NATURE
--4 color civilization combinations
CIVILIZATIONS_LWDF		=0x0f	--CIVILIZATIONS_LWD+CIVILIZATION_FIRE
--5 color civilization combinations
CIVILIZATIONS_LWDFN		=0x1f	--CIVILIZATIONS_LWDF+CIVILIZATION_NATURE
--Race (0x1-0x7ff)
RACE_CYBER_LORD			=0x1	--Introduced by "Aqua Seneschal" (1TVR 1/43)
RACE_TRENCH_HUNTER		=0x2	--Introduced by "Frogzooka" (1TVR 2/43)
RACE_UNDERTOW_ENGINE	=0x3	--Introduced by "Hydrobot Crab" (1TVR 4/43)
RACE_LEVIATHAN			=0x4	--Introduced by "King Nautilus" (1TVR 6/43)
RACE_ROT_WORM			=0x5	--Introduced by "Brain Squirmer" (1TVR 12/43)
RACE_SPECTER			=0x6	--Introduced by "Dream Pirate" (1TVR 14/43)
RACE_TARBORG			=0x7	--Introduced by "Fumes" (1TVR 15/43)
RACE_CHIMERA			=0x8	--Introduced by "Gigargon" (1TVR 16/43)
RACE_BRAIN_JACKER		=0x9	--Introduced by "Skeeter Swarmer" (1TVR 19/43)
RACE_DREAD_MASK			=0xa	--Introduced by "Skull Cutter" (1TVR 20/43)
RACE_SHADOW_CHAMPION	=0xb	--Introduced by "Zagaan, the Bone Knight" (1TVR 22/43)
RACE_BURN_BELLY			=0xc	--Introduced by "Blaze Belcher" (1TVR 23/43)
RACE_ATTACK_RAPTOR		=0xd	--Introduced by "Draglide the Swiftest" (1TVR 25/43)
RACE_ROCK_BRUTE			=0xe	--Introduced by "Flametropus" (1TVR 26/43)
RACE_DUNE_GECKO			=0xf	--Introduced by "Little Hissy" (1TVR 28/43)
RACE_DRAKON				=0x10	--Introduced by "Pyro Trooper" (1TVR 30/43)
RACE_STOMPER			=0x11	--Introduced by "Simian Trooper Grash" (1TVR 32/43)
RACE_MEGABUG			=0x12	--Introduced by "Ambush Scorpion" (1TVR 34/43)
RACE_COLOSSUS			=0x13	--Introduced by "Brave Giant" (1TVR 35/43)
RACE_BEAST_KIN			=0x14	--Introduced by "Bronze-Arm Tribe" (1TVR 36/43)
RACE_TREE_KIN			=0x15	--Introduced by "Essence Elf" (1TVR 37/43)
RACE_TUSKER				=0x16	--Introduced by "Rumbling Terrasaur" (1TVR 42/43)
RACE_EVIL_TOY			=0x17	--Introduced by "Razorkinder" (1TVR S1/S2)
RACE_ARMORED_DRAGON		=0x18	--Introduced by "Tatsurion" (1TVR S2/S2)
RACE_ENFORCER			=0x19	--Introduced by "Blinder Beetle" (2DED 1/55)
RACE_STORM_PATROL		=0x1a	--Introduced by "Grand Gure, Tower Keeper" (2DED 2/55)
RACE_STAR_SENTINEL		=0x1b	--Introduced by "Star Lantern" (2DED 9/55)
RACE_AQUAN				=0x1c	--Introduced by "Aqua Commando" (2DED 12/55)
RACE_ZOMBIE				=0x1d	--Introduced by "Writhing Bone Ghoul" (2DED 33/55)
RACE_SPIRIT_TOTEM		=0x1e	--Introduced by "Chief Many-Tribes" (2DED 46/55)
RACE_WILD_VEGGIE		=0x1f	--Introduced by "Karate Carrot" (2DED 49/55)
RACE_SKYFORCE_CHAMPION	=0x20	--Introduced by "Alcadeus, Winged Justice" (2DED S1/S5)
RACE_EARTHSTRIKE_DRAGON	=0x21	--Introduced by "Terradragon Regarion Doom" (2DED S5/S5)
RACE_BATTLE_SPHERE		=0x22	--Introduced by "Argus, Vigilant Seer" (3RIS 1/165)
RACE_FRACTAL			=0x23	--Introduced by "Seer Serpent" (3RIS 23/165)
RACE_CYBER_VIRUS		=0x24	--Introduced by "Memory Swarm" (3RIS 54/165)
RACE_EARTH_EATER		=0x25	--Introduced by "Midnight Crawler" (3RIS 55/165)
RACE_FIRE_BIRD			=0x26	--Introduced by "Kenina the Igniter" (3RIS 115/165)
RACE_BERSERKER			=0x27	--Introduced by "Vorg" (3RIS 132/165)
RACE_FLYING_FUNGUS		=0x28	--Introduced by "Drifting Toadstool" (3RIS 139/165)
RACE_LIVING_CITY		=0x29	--Introduced by "Shell Dome" (3RIS 158/165)
RACE_ANGEL_COMMAND		=0x2a	--Introduced by "Sasha, Channeler of Light" (3RIS S3/S15)
RACE_DARK_LORD			=0x2b	--Introduced by "Megaria, the Collector" (3RIS S9/S15)
RACE_CELESTIAL_DRAGON	=0x2c	--Introduced by "Orion, Radiant Fury" (4EVO S1/S5)
RACE_TERROR_DRAGON		=0x2d	--Introduced by "Necrodragon of Vile Ichor" (5DRA 1/2)
RACE_SKY_WEAVER			=0x2e	--Introduced by "Arachnopod" (6DSI 1/55)
RACE_INVADER			=0x2f	--Introduced by "Vectro Scout" (6DSI 11/55)
RACE_TSUNAMI_DRAGON		=0x30	--Introduced by "Dragon of Reflections" (6DSI 14/55)
RACE_MELT_WARRIOR		=0x31	--Introduced by "Explosive Infantry" (6DSI 39/55)
RACE_MECHA_THUNDER		=0x32	--Introduced by "Spire Zealot" (7CLA 12/110)
RACE_SPIRIT_QUARTZ		=0x33	--Introduced by "Sunspout Quartz" (7CLA 77/110)
RACE_MONARCH			=0x34	--Introduced by "King Tritonus" (7CLA S2/S10)
RACE_CYBER_COMPLEX		=0x35	--Introduced by "Finbarr's Dreadnought" (9SHA 14/80)
RACE_RIPTIDE_CHAMPION	=0x36	--Introduced by "Krazzix the Volatile" (9SHA 61/80)
RACE_BLAZE_CHAMPION		=0x37	--Introduced by "Krazzix the Volatile" (9SHA 61/80)
RACE_INFERNO_COMPLEX	=0x38	--Introduced by "Skycrusher's Volcano-Ship" (9SHA 30/80)
RACE_PRIMAL_CHAMPION	=0x39	--Introduced by "Wildstrider Ramnoth" (9SHA S5/S10)
RACE_CORRUPTED			=0x3a	--Introduced by "Aqua Trickster" (10INV 8/80)
RACE_MYSTIC				=0x3b	--Introduced by "The Mystic of Water" (12MYS 20/55)
RACE_HUMAN				=0x3c	--Introduced by "Humonguru" (12MYS S4/S5)
RACE_MIMIC				=0x3d	--Introduced by "Horror Box" (13GAU 77/160)
RACE_VOID_SPAWN			=0x3e	--Introduced by "Cloud Grappler" (15VTX 8/160)
RACE_SNOW_SPRITE		=0x3f	--Introduced by "Solstice Chanter" (15VTX 147/160)
RACE_SURVIVOR			=0x40	--Introduced by "The Chronarch" (15VTX S2/S10)
--Race Category (0x800-0x9ff)
RACECAT_DRAGON			=0x800	--Supported by "Lux" (6DSI 6/55)
--Name Category (0xa00-0xfff)
NAMECAT_TATSURION		=0xa00	--Supported by "Tatsurion the Relentless" (7CLA S10/S10)
NAMECAT_SCARADORABLE	=0xa01	--Supported by "Tatsurion the Brawler" (10INV S10/S10)
NAMECAT_GLUURRGLE		=0xa02	--Supported by "Tatsurion the Brawler" (10INV S10/S10)
NAMECAT_VALKO			=0xa03	--Supported by "Valko" (15VTX 101/160)
--Reason
--The reason for sending a card to another location
REASON_BANISH		=0x1		--Banished
REASON_RELEASE		=0x2		--(unused)
REASON_TEMPORARY	=0x4		--Temporarily moved
REASON_MATERIAL		=0x8		--(unused)
REASON_SUMMON		=0x10		--(unused)
REASON_BATTLE		=0x20		--Battle banished
REASON_EFFECT		=0x40		--Effect
REASON_COST			=0x80		--Cost
REASON_ADJUST		=0x100		--(unused)
REASON_LOST_TARGET	=0x200		--(unused)
REASON_RULE			=0x400		--Rule
REASON_SPSUMMON		=0x800		--(unused)
REASON_DISSUMMON	=0x1000		--(unused)
REASON_FLIP			=0x2000		--(unused)
REASON_DISCARD		=0x4000		--Discarded
REASON_RDAMAGE		=0x8000		--(unused)
REASON_RRECOVER		=0x10000	--(unused)
REASON_RETURN		=0x20000	--(unused)
REASON_FUSION		=0x40000	--(unused)
REASON_SYNCHRO		=0x80000	--(unused)
REASON_RITUAL		=0x100000	--(unused)
REASON_XYZ			=0x200000	--(unused)
REASON_REPLACE		=0x1000000	--Substituted
REASON_DRAW			=0x2000000	--(unused)
REASON_REDIRECT		=0x4000000	--(unused)
REASON_REVEAL		=0x8000000	--(unused)
REASON_LINK			=0x10000000	--(unused)
REASON_BREAK		=0x20000000	--Shield broken
--Location Reason
LOCATION_REASON_TOFIELD		=0x1	--(unused)
LOCATION_REASON_CONTROL		=0x2	--(unused)
LOCATION_REASON_COUNT		=0x4	--(unused, only available in YGOPro Percy)
--Win Reason
WIN_REASON_DECKOUT		=0x2	--Ran out of cards in the deck
WIN_REASON_INVALID		=0x10	--(reserved) Invalid deck
WIN_REASON_MYSTIC_LIGHT	=0x11	--The Mystic of Light
--Summon Type
SUMMON_TYPE_NORMAL		=0x10000000	--(unused)
SUMMON_TYPE_ADVANCE		=0x11000000	--(unused)
SUMMON_TYPE_DUAL		=0x12000000	--(unused)
SUMMON_TYPE_FLIP		=0x20000000	--(unused)
SUMMON_TYPE_SPECIAL		=0x40000000	--(unused)
SUMMON_TYPE_FUSION		=0x43000000	--(unused)
SUMMON_TYPE_RITUAL		=0x45000000	--(unused)
SUMMON_TYPE_SYNCHRO		=0x46000000	--(unused)
SUMMON_TYPE_NONEVOLVE	=0x49000000	--Summon by paying mana
SUMMON_TYPE_EVOLVE		=0x49000100	--Evolve
SUMMON_TYPE_PENDULUM	=0x4a000000	--(unused)
SUMMON_TYPE_LINK		=0x4c000000	--(unused)
--Summon Value
SUMMON_VALUE_SELF					=0x1	--(unused)
SUMMON_VALUE_DARK_FUSION			=0x10	--(unused)
SUMMON_VALUE_BLACK_GARDEN			=0x11	--(unused)
SUMMON_VALUE_SYNCHRO_MATERIAL		=0x12	--(unused)
SUMMON_VALUE_DARK_SANCTUARY			=0x13	--(unused)
SUMMON_VALUE_MILLENNIUM_REVELATION	=0x14	--(unused)
SUMMON_VALUE_LV						=0x1000	--(unused)
SUMMON_VALUE_GLADIATOR				=0x2000	--(unused)
SUMMON_VALUE_EVOLTILE				=0x4000	--(unused)
--Card Status
STATUS_DISABLED				=0x0001		--(unused)
STATUS_TO_ENABLE			=0x0002		--(unused)
STATUS_TO_DISABLE			=0x0004		--(unused)
STATUS_PROC_COMPLETE		=0x0008		--(unused)
STATUS_SET_TURN				=0x0010		--(unused)
STATUS_NO_LEVEL				=0x0020		--(unused)
STATUS_BATTLE_RESULT		=0x0040		--(unused)
STATUS_SPSUMMON_STEP		=0x0080		--(unused)
STATUS_FORM_CHANGED			=0x0100		--(unused)
STATUS_SUMMONING			=0x0200		--(unused)
STATUS_EFFECT_ENABLED		=0x0400		--(unused)
STATUS_SUMMON_TURN			=0x0800		--(unused)
STATUS_BANISH_CONFIRMED		=0x1000		--Confirmed to banished
STATUS_LEAVE_CONFIRMED		=0x2000		--(unused)
STATUS_BATTLE_BANISHED		=0x4000		--Lost a battle
STATUS_COPYING_EFFECT		=0x8000		--Copying another card's effect
STATUS_CHAINING				=0x10000	--(unused)
STATUS_SUMMON_DISABLED		=0x20000	--(unused)
STATUS_ACTIVATE_DISABLED	=0x40000	--(unused)
STATUS_EFFECT_REPLACED		=0x80000	--(unused)
STATUS_FUTURE_FUSION		=0x100000	--(unused)
STATUS_ATTACK_CANCELED		=0x200000	--Attacking card's attack is negated
STATUS_INITIALIZING			=0x400000	--(unused)
STATUS_ACTIVATED			=0x800000	--(unused, only available in YGOPro Percy)
STATUS_JUST_POS				=0x1000000	--(unused)
STATUS_CONTINUOUS_POS		=0x2000000	--(unused)
STATUS_FORBIDDEN			=0x4000000	--(unused)
STATUS_ACT_FROM_HAND		=0x8000000	--(unused)
STATUS_OPPO_BATTLE			=0x10000000	--(unused)
STATUS_FLIP_SUMMON_TURN		=0x20000000	--(unused)
STATUS_TO_BZONE_TURN		=0x40000000	--Put into the battle zone this turn
--Assume
ASSUME_CODE			=1	--(unused)
ASSUME_TYPE			=2	--(unused)
ASSUME_LEVEL		=3	--(unused)
ASSUME_RANK			=4	--(unused)
ASSUME_ATTRIBUTE	=5	--(unused)
ASSUME_RACE			=6	--(unused)
ASSUME_ATTACK		=7	--(unused)
ASSUME_DEFENSE		=8	--(unused)
ASSUME_LINK			=9	--(unused, only available in YGOPro Percy)
ASSUME_LINKMARKER	=10	--(unused, only available in YGOPro Percy)
--Link Marker
LINK_MARKER_BOTTOM_LEFT		=0x001	--(unused)
LINK_MARKER_BOTTOM			=0x002	--(unused)
LINK_MARKER_BOTTOM_RIGHT	=0x004	--(unused)
LINK_MARKER_LEFT			=0x008	--(unused)
LINK_MARKER_RIGHT			=0x020	--(unused)
LINK_MARKER_TOP_LEFT		=0x040	--(unused)
LINK_MARKER_TOP				=0x080	--(unused)
LINK_MARKER_TOP_RIGHT		=0x100	--(unused)
--Counter
COUNTER_WITHOUT_PERMIT		=0x1000	--(unused)
COUNTER_NEED_ENABLE			=0x2000	--(unused)
--Phase
PHASE_DRAW			=0x01	--Draw Phase
PHASE_STANDBY		=0x02	--Standby Phase
PHASE_MAIN1			=0x04	--Main Phase 1
PHASE_BATTLE_START	=0x08	--Start Step
PHASE_BATTLE_STEP	=0x10	--Battle Step
PHASE_DAMAGE		=0x20	--Damage Step
PHASE_DAMAGE_CAL	=0x40	--Damage calculation
PHASE_BATTLE		=0x80	--End Step
PHASE_MAIN2			=0x100	--Main Phase 2
PHASE_END			=0x200	--End Phase
--Player
PLAYER_ONE			=0		--Player who goes first
PLAYER_TWO			=1		--Player who goes second
PLAYER_NONE			=2		--No players
PLAYER_ALL			=3		--All players
PLAYER_OWNER		=nil	--player=PLAYER_OWNER in Duel.Sendto..(targets, player, reason)
PLAYER_SELF			=0		--player=PLAYER_SELF in Effect.SetCondition(Auxiliary.Function(player)), etc.
PLAYER_OPPO			=1		--player=PLAYER_OPPO in Effect.SetCondition(Auxiliary.Function(player)), etc.
--Chain Information
CHAININFO_CHAIN_COUNT			=0x01	--(unused)
CHAININFO_TRIGGERING_EFFECT		=0x02	--(unused)
CHAININFO_TRIGGERING_PLAYER		=0x04	--(unused)
CHAININFO_TRIGGERING_CONTROLER	=0x08	--(unused)
CHAININFO_TRIGGERING_LOCATION	=0x10	--(unused)
CHAININFO_TRIGGERING_SEQUENCE	=0x20	--(unused)
CHAININFO_TARGET_CARDS			=0x40	--(unused)
CHAININFO_TARGET_PLAYER			=0x80	--(unused)
CHAININFO_TARGET_PARAM			=0x100	--(unused)
CHAININFO_DISABLE_REASON		=0x200	--(unused)
CHAININFO_DISABLE_PLAYER		=0x400	--(unused)
CHAININFO_CHAIN_ID				=0x800	--(unused)
CHAININFO_TYPE					=0x1000	--(unused)
CHAININFO_EXTTYPE				=0x2000	--(unused)
CHAININFO_TRIGGERING_POSITION	=0x4000	--(unused)
--The following is not available in YGOPro Percy
CHAININFO_TRIGGERING_CODE		=0x8000		--(unused)
CHAININFO_TRIGGERING_CODE2		=0x10000	--(unused)
CHAININFO_TRIGGERING_LEVEL		=0x40000	--(unused)
CHAININFO_TRIGGERING_RANK		=0x80000	--(unused)
CHAININFO_TRIGGERING_ATTRIBUTE	=0x100000	--(unused)
CHAININFO_TRIGGERING_RACE		=0x200000	--(unused)
CHAININFO_TRIGGERING_ATTACK		=0x400000	--(unused)
CHAININFO_TRIGGERING_DEFENSE	=0x800000	--(unused)
--Reset
RESET_SELF_TURN		=0x10000000			--(unused, combined with RESET_PHASE)
RESET_OPPO_TURN		=0x20000000			--(unused, combined with RESET_PHASE)
RESET_PHASE			=0x40000000			--Reset in a specific phase (combined with PHASE constant)
RESET_CHAIN			=0x80000000			--Reset when a Chain resolves
RESET_EVENT			=0x1000				--Reset under a specified condition (combined with following events)
RESET_CARD			=0x2000				--(unused)
RESET_CODE			=0x4000				--(unused)
RESET_COPY			=0x8000				--(unused)
--The following is used in combination with RESET_EVENT in SetReset
RESET_DISABLE		=0x00010000			--Reset when effect is negated (only applicable to owner==effect handler)
RESET_TURN_SET		=0x00020000			--(unused)
RESET_TOMANA		=0x00040000			--(unused)
RESET_TODPILE		=0x00080000			--Reset when put into the discard pile
RESET_TEMP_REMOVE	=0x00100000			--(unused)
RESET_TOHAND		=0x00200000			--Reset when put into the hand
RESET_TODECK		=0x00400000			--Reset when put into the deck
RESET_LEAVE			=0x00800000			--Reset when left the battle zone
RESET_TOFIELD		=0x01000000			--(unused)
RESET_CONTROL		=0x02000000			--(unused)
RESET_OVERLAY		=0x04000000			--(unused)
RESET_MSCHANGE		=0x08000000			--(unused)
--Reset combinations
RESETS_STANDARD		=0x1fe0000			--RESET_TURN_SET+RESET_TOMANA+RESET_TODPILE+RESET_TEMP_REMOVE+RESET_TOHAND+RESET_TODECK+RESET_LEAVE+RESET_TOFIELD
RESETS_REDIRECT		=0xc7e0000			--RESETS_STANDARD+RESET_OVERLAY+RESET_MSCHANGE-RESET_LEAVE-RESET_TOFIELD (EFFECT_LEAVE_FIELD_REDIRECT)
--Effect Type
--Classification of effects
EFFECT_TYPE_SINGLE			=0x0001		--Effect applied to only a single card on the field
EFFECT_TYPE_FIELD			=0x0002		--Effect applied to all cards/players in a location
EFFECT_TYPE_EQUIP			=0x0004		--(unused)
EFFECT_TYPE_ACTIONS			=0x0008		--(unused)
EFFECT_TYPE_ACTIVATE		=0x0010		--(unused)
EFFECT_TYPE_FLIP			=0x0020		--(unused)
EFFECT_TYPE_IGNITION		=0x0040		--Ignition Effect
EFFECT_TYPE_TRIGGER_O		=0x0080		--Optional Trigger Effect
EFFECT_TYPE_QUICK_O			=0x0100		--Optional Quick Effect
EFFECT_TYPE_TRIGGER_F		=0x0200		--Mandatory Trigger Effect
EFFECT_TYPE_QUICK_F			=0x0400		--Mandatory Quick Effect
EFFECT_TYPE_CONTINUOUS		=0x0800		--Continuous Effect, non-Chaining effect
EFFECT_TYPE_XMATERIAL		=0x1000		--(unused)
EFFECT_TYPE_GRANT			=0x2000		--Effect granted to another card
EFFECT_TYPE_TARGET			=0x4000		--(unused, not available in YGOPro Percy)
--Flag
--Characteristics of effects
EFFECT_FLAG_INITIAL				=0x0001		--(unused)
EFFECT_FLAG_FUNC_VALUE			=0x0002		--(unused)
EFFECT_FLAG_COUNT_LIMIT			=0x0004		--(unused)
EFFECT_FLAG_FIELD_ONLY			=0x0008		--(unused)
EFFECT_FLAG_CARD_TARGET			=0x0010		--Targets cards
EFFECT_FLAG_IGNORE_RANGE		=0x0020		--Affects cards in all locations
EFFECT_FLAG_ABSOLUTE_TARGET		=0x0040		--(unused)
EFFECT_FLAG_IGNORE_IMMUNE		=0x0080		--Ignores effect immunity
EFFECT_FLAG_SET_AVAILABLE		=0x0100		--Affects face-down cards on the field
EFFECT_FLAG_CANNOT_NEGATE		=0x0200		--(unused)
EFFECT_FLAG_CANNOT_DISABLE		=0x0400		--Cannot be negated
EFFECT_FLAG_PLAYER_TARGET		=0x0800		--Targets players
EFFECT_FLAG_BOTH_SIDE			=0x1000		--(unused)
EFFECT_FLAG_COPY_INHERIT		=0x2000		--(unused)
EFFECT_FLAG_DAMAGE_STEP			=0x4000		--Can be activated during the Damage Step (not required for EFFECT_TYPE_SINGLE)
EFFECT_FLAG_DAMAGE_CAL			=0x8000		--Can be activated during damage calculation (not required for EFFECT_TYPE_SINGLE)
EFFECT_FLAG_DELAY				=0x10000	--Optional Trigger Effect cannot miss timing
EFFECT_FLAG_SINGLE_RANGE		=0x20000	--Sets the range of EFFECT_TYPE_SINGLE effects
EFFECT_FLAG_UNCOPYABLE			=0x40000	--Cannot be copied
EFFECT_FLAG_OATH				=0x80000	--(unused)
EFFECT_FLAG_SUMMON_PARAM		=0x100000	--Enables SetTargetRange to specify the summoning destination and position
EFFECT_FLAG_REPEAT				=0x200000	--(unused)
EFFECT_FLAG_NO_TURN_RESET		=0x400000	--"Once while face-up on the field"
EFFECT_FLAG_EVENT_PLAYER		=0x800000	--(unused)
EFFECT_FLAG_OWNER_RELATE		=0x1000000	--(unused)
EFFECT_FLAG_AVAILABLE_BD		=0x2000000	--(N/A)
EFFECT_FLAG_CLIENT_HINT			=0x4000000	--Enables a tooltip of the effect (can only be used outside initial_effect)
EFFECT_FLAG_CHAIN_UNIQUE		=0x8000000	--(N/A)
EFFECT_FLAG_LIMIT_ZONE			=0x10000000	--(unused, not available in YGOPro Percy)
EFFECT_FLAG_CHAIN_LIMIT			=0x20000000	--Cannot be Chained to
EFFECT_FLAG_COME_INTO_PLAY		=0x40000000	--"When this/another creature enters the battle zone"
EFFECT_FLAG_IMMEDIATELY_APPLY	=0x80000000	--(unused)

EFFECT_FLAG2_NAGA				=0x0001		--(N/A)
EFFECT_FLAG2_COF				=0x0002		--(unused)
EFFECT_FLAG2_MAJESTIC_MUST_COPY	=0x80000000	--(unused, only available in YGOPro Percy)
--Effect Code
EFFECT_IMMUNE_EFFECT				=1		--(unused)
EFFECT_DISABLE						=2		--(unused)
EFFECT_CANNOT_DISABLE				=3		--(unused)
EFFECT_SET_CONTROL					=4		--(unused)
EFFECT_CANNOT_CHANGE_CONTROL		=5		--(unused)
EFFECT_CANNOT_ACTIVATE				=6		--Player cannot activate effects
EFFECT_CANNOT_TRIGGER				=7		--Card cannot activate effects
EFFECT_DISABLE_EFFECT				=8		--(unused)
EFFECT_DISABLE_CHAIN				=9		--(unused)
EFFECT_DISABLE_TRAPMONSTER			=10		--(unused)
EFFECT_CANNOT_INACTIVATE			=12		--(unused)
EFFECT_CANNOT_DISEFFECT				=13		--(unused)
EFFECT_CANNOT_CHANGE_POSITION		=14		--Cannot change position
EFFECT_TRAP_ACT_IN_HAND				=15		--(unused)
EFFECT_TRAP_ACT_IN_SET_TURN			=16		--(unused)
EFFECT_REMAIN_FIELD					=17		--(unused)
EFFECT_MONSTER_SSET					=18		--Monster can be Set in the Spell & Trap Zone
EFFECT_CANNOT_SUMMON				=20		--Cannot Normal Summon monsters
EFFECT_CANNOT_FLIP_SUMMON			=21		--(unused)
EFFECT_CANNOT_SUMMON_CREATURE		=22		--Cannot summon creatures
EFFECT_CANNOT_MSET					=23		--Cannot Set monsters
EFFECT_CANNOT_SSET					=24		--Cannot Set Spells/Traps
EFFECT_CANNOT_DRAW					=25		--(unused)
EFFECT_CANNOT_DISABLE_SUMMON		=26		--(unused)
EFFECT_CANNOT_DISABLE_SPSUMMON		=27		--(unused)
EFFECT_SET_SUMMON_COUNT_LIMIT		=28		--(unused)
EFFECT_EXTRA_SUMMON_COUNT			=29		--(unused)
EFFECT_TO_BZONE_CONDITION			=30		--Condition to put a creature into the battle zone
EFFECT_REVIVE_LIMIT					=31		--(unused)
EFFECT_SUMMON_PROC					=32		--(unused)
EFFECT_LIMIT_SUMMON_PROC			=33		--(unused)
EFFECT_SUMMON_CREATURE_PROC			=34		--Creature summoning procedure
EFFECT_EXTRA_SET_COUNT				=35		--(unused)
EFFECT_SET_PROC						=36		--(unused)
EFFECT_LIMIT_SET_PROC				=37		--(unused)
EFFECT_DEVINE_LIGHT					=38		--(unused)
EFFECT_CANNOT_DISABLE_FLIP_SUMMON	=39		--(unused)
EFFECT_UNBANISHABLE					=40		--Cannot be banished
EFFECT_UNBANISHABLE_EFFECT			=41		--Cannot be banished by effects
EFFECT_UNBANISHABLE_BATTLE			=42		--Cannot be banished by battle
EFFECT_UNRELEASABLE_SUM				=43		--(unused)
EFFECT_UNRELEASABLE_NONSUM			=44		--(unused)
EFFECT_DESTROY_SUBSTITUTE			=45		--(unused)
EFFECT_CANNOT_RELEASE				=46		--(unused)
EFFECT_INDESTRUCTIBLE_COUNT			=47		--(unused)
EFFECT_UNRELEASABLE_EFFECT			=48		--(unused)
EFFECT_BANISH_REPLACE				=50		--Substitute a card being banished with another action
EFFECT_RELEASE_REPLACE				=51		--(unused)
EFFECT_SEND_REPLACE					=52		--Put a card into another location instead of X
EFFECT_CANNOT_DISCARD_HAND			=55		--Player cannot discard cards from hand
EFFECT_CANNOT_DISCARD_DECK			=56		--(unused)
EFFECT_CANNOT_USE_AS_COST			=57		--(unused)
EFFECT_CANNOT_PLACE_COUNTER			=58		--(unused)
EFFECT_CANNOT_TO_GRAVE_AS_COST		=59		--(unused)
EFFECT_LEAVE_FIELD_REDIRECT			=60		--(unused)
EFFECT_TO_HAND_REDIRECT				=61		--(unused)
EFFECT_TO_DECK_REDIRECT				=62		--(unused)
EFFECT_TO_MZONE_REDIRECT			=63		--Put a card into another location instead of the mana zone
EFFECT_TO_DPILE_REDIRECT			=64		--Put a card into another location instead of the discard pile
EFFECT_CANNOT_TO_HAND				=65		--Cannot be put into the hand
EFFECT_CANNOT_TO_DECK				=66		--Cannot be put into the deck
EFFECT_CANNOT_TO_DPILE				=67		--Cannot be put into the discard pile
EFFECT_CANNOT_TO_MZONE				=68		--Cannot be put into the mana zone
EFFECT_CANNOT_TURN_SET				=69		--(unused)
EFFECT_CANNOT_BE_BATTLE_TARGET		=70		--Cannot be targeted for attacks
EFFECT_CANNOT_BE_EFFECT_TARGET		=71		--Cannot be targeted by effects
EFFECT_IGNORE_BATTLE_TARGET			=72		--(unused)
EFFECT_CANNOT_ATTACK_PLAYER			=73		--Cannot attack player
EFFECT_ATTACK_PLAYER				=74		--Can attack player
EFFECT_DUAL_STATUS					=75		--(unused)
EFFECT_EQUIP_LIMIT					=76		--(unused)
EFFECT_DUAL_SUMMONABLE				=77		--(unused)
EFFECT_REVERSE_DAMAGE				=80		--(unused)
EFFECT_REVERSE_RECOVER				=81		--(unused)
EFFECT_CHANGE_DAMAGE				=82		--(unused)
EFFECT_REFLECT_DAMAGE				=83		--(unused)
EFFECT_CANNOT_ATTACK				=85		--Cannot attack
EFFECT_CANNOT_ATTACK_ANNOUNCE		=86		--(unused)
EFFECT_CANNOT_CHANGE_POS_E			=87		--(unused)
EFFECT_ACTIVATE_COST				=90		--(unused)
EFFECT_SUMMON_COST					=91		--(unused)
EFFECT_SPSUMMON_COST				=92		--(unused)
EFFECT_FLIPSUMMON_COST				=93		--(unused)
EFFECT_MSET_COST					=94		--(unused)
EFFECT_SSET_COST					=95		--(unused)
EFFECT_ATTACK_COST					=96		--(unused)

EFFECT_UPDATE_POWER					=100	--Increase/decrease power
EFFECT_SET_ATTACK					=101	--(unused)
EFFECT_SET_ATTACK_FINAL				=102	--(unused)
EFFECT_SET_BASE_ATTACK				=103	--(unused)
EFFECT_UPDATE_DEFENSE				=104	--(unused)
EFFECT_SET_DEFENSE					=105	--(unused)
EFFECT_SET_DEFENSE_FINAL			=106	--(unused)
EFFECT_SET_BASE_DEFENSE				=107	--Set original DEF
EFFECT_REVERSE_UPDATE				=108	--(unused)
EFFECT_SWAP_AD						=109	--(unused)
EFFECT_SWAP_BASE_AD					=110	--(unused)
EFFECT_SWAP_ATTACK_FINAL			=111	--(N/A)
EFFECT_SWAP_DEFENSE_FINAL			=112	--(N/A)
EFFECT_ADD_CODE						=113	--(unused)
EFFECT_CHANGE_CODE					=114	--(unused)
EFFECT_ADD_TYPE						=115	--(unused)
EFFECT_REMOVE_TYPE					=116	--(unused)
EFFECT_CHANGE_TYPE					=117	--(unused)
EFFECT_ADD_RACE						=120	--(unused)
EFFECT_REMOVE_RACE					=121	--(unused)
EFFECT_CHANGE_RACE					=122	--(unused)
EFFECT_ADD_ATTRIBUTE				=125	--(unused)
EFFECT_REMOVE_ATTRIBUTE				=126	--(unused)
EFFECT_CHANGE_ATTRIBUTE				=127	--(unused)
EFFECT_UPDATE_PLAY_COST				=130	--Increase/decrease the mana cost required for playing a card
EFFECT_CHANGE_MANA_COST				=131	--Set mana cost
EFFECT_UPDATE_RANK					=132	--(unused)
EFFECT_CHANGE_RANK					=133	--(unused)
EFFECT_UPDATE_LSCALE				=134	--(unused)
EFFECT_CHANGE_LSCALE				=135	--(unused)
EFFECT_UPDATE_RSCALE				=136	--(unused)
EFFECT_CHANGE_RSCALE				=137	--(unused)
EFFECT_SET_POSITION					=140	--(unused)
EFFECT_SELF_DESTROY					=141	--(unused)
EFFECT_SELF_TOGRAVE					=142	--(unused)
EFFECT_DOUBLE_TRIBUTE				=150	--(unused)
EFFECT_DECREASE_TRIBUTE				=151	--(unused)
EFFECT_DECREASE_TRIBUTE_SET			=152	--(unused)
EFFECT_EXTRA_RELEASE				=153	--(unused)
EFFECT_TRIBUTE_LIMIT				=154	--(unused)
EFFECT_EXTRA_RELEASE_SUM			=155	--(unused)
EFFECT_TRIPLE_TRIBUTE				=156	--(N/A)
EFFECT_ADD_EXTRA_TRIBUTE			=157	--(unused, not available in YGOPro Percy)
EFFECT_EXTRA_RELEASE_NONSUM			=158	--(unused, not available in YGOPro Percy)
EFFECT_PUBLIC						=160	--(unused)
EFFECT_COUNTER_PERMIT				=0x10000--(unused)
EFFECT_COUNTER_LIMIT				=0x20000--(unused)
EFFECT_RCOUNTER_REPLACE				=0x30000--(unused)
EFFECT_LPCOST_CHANGE				=170	--(unused)
EFFECT_LPCOST_REPLACE				=171	--(unused)
EFFECT_SKIP_DP						=180	--Skip Draw Phase
EFFECT_SKIP_SP						=181	--Skip Standby Phase
EFFECT_SKIP_M1						=182	--(unused) Skip Main Phase 1
EFFECT_SKIP_BP						=183	--(unused) Skip Battle Phase
EFFECT_SKIP_M2						=184	--(unused) Skip Main Phase 2
EFFECT_CANNOT_BP					=185	--(unused) Cannot conduct Battle Phase
EFFECT_CANNOT_M2					=186	--Cannot conduct Main Phase 2
EFFECT_CANNOT_EP					=187	--(unused) Cannot conduct End Phase
EFFECT_SKIP_TURN					=188	--(unused)
EFFECT_DEFENSE_ATTACK				=190	--(unused)
EFFECT_MUST_ATTACK					=191	--Must attack if able
EFFECT_FIRST_ATTACK					=192	--(unused)
EFFECT_ATTACK_ALL					=193	--(unused)
EFFECT_EXTRA_ATTACK					=194	--Increase the number of attacks
EFFECT_MUST_BE_ATTACKED				=195	--Must be attacked (only available in YGOPro Percy)
EFFECT_ONLY_BE_ATTACKED				=196	--(unused)
EFFECT_ATTACK_DISABLED				=197	--(unused)
EFFECT_NO_BATTLE_DAMAGE				=200	--(unused)
EFFECT_AVOID_BATTLE_DAMAGE			=201	--Take no battle damage from attacks involving this card
EFFECT_REFLECT_BATTLE_DAMAGE		=202	--(unused)
EFFECT_PIERCE						=203	--(unused)
EFFECT_BATTLE_DESTROY_REDIRECT		=204	--(unused)
EFFECT_BATTLE_DAMAGE_TO_EFFECT		=205	--(unused)
EFFECT_BOTH_BATTLE_DAMAGE			=206	--(unused, not available in YGOPro Percy)
EFFECT_ALSO_BATTLE_DAMAGE			=207	--(unused, not available in YGOPro Percy)
EFFECT_CHANGE_BATTLE_DAMAGE			=208	--(unused, not available in YGOPro Percy)
EFFECT_TOSS_COIN_REPLACE			=220	--(unused)
EFFECT_TOSS_DICE_REPLACE			=221	--(unused)
EFFECT_FUSION_MATERIAL				=230	--(unused)
EFFECT_CHAIN_MATERIAL				=231	--(unused)
EFFECT_SYNCHRO_MATERIAL				=232	--(unused)
EFFECT_XYZ_MATERIAL					=233	--(unused)
EFFECT_FUSION_SUBSTITUTE			=234	--(unused)
EFFECT_CANNOT_BE_FUSION_MATERIAL	=235	--(unused)
EFFECT_CANNOT_BE_SYNCHRO_MATERIAL	=236	--(unused)
EFFECT_SYNCHRO_MATERIAL_CUSTOM		=237	--(unused)
EFFECT_CANNOT_BE_XYZ_MATERIAL		=238	--(unused)
EFFECT_CANNOT_BE_LINK_MATERIAL		=239	--(unused)
EFFECT_SYNCHRO_LEVEL				=240	--(unused)
EFFECT_RITUAL_LEVEL					=241	--(unused)
EFFECT_XYZ_LEVEL					=242	--(unused)
EFFECT_EXTRA_RITUAL_MATERIAL		=243	--(unused)
EFFECT_NONTUNER						=244	--(unused)
EFFECT_OVERLAY_REMOVE_REPLACE		=245	--(unused)
EFFECT_SCRAP_CHIMERA				=246	--(unused)
EFFECT_TUNE_MAGICIAN_X				=247	--(unused)
EFFECT_TUNE_MAGICIAN_F				=248	--(unused, not available in YGOPro Percy)
EFFECT_PRE_MONSTER					=250	--(unused)
EFFECT_MATERIAL_CHECK				=251	--(unused)
EFFECT_DISABLE_FIELD				=260	--(unused)
EFFECT_USE_EXTRA_MZONE				=261	--(unused)
EFFECT_USE_EXTRA_SZONE				=262	--(unused)
EFFECT_MAX_MZONE					=263	--(unused)
EFFECT_MAX_SZONE					=264	--(unused)
EFFECT_FORCE_MZONE					=265	--(unused, only available in YGOPro Percy)
EFFECT_BECOME_LINKED_ZONE			=266	--(unused, only available in YGOPro Percy)
EFFECT_HAND_LIMIT					=270	--Change the hand size limit
EFFECT_DRAW_COUNT					=271	--(unused)
EFFECT_SPIRIT_DONOT_RETURN			=280	--(unused)
EFFECT_SPIRIT_MAYNOT_RETURN			=281	--(unused)
EFFECT_CHANGE_ENVIRONMENT			=290	--(unused)
EFFECT_NECRO_VALLEY					=291	--(unused)
EFFECT_FORBIDDEN					=292	--(unused)
EFFECT_NECRO_VALLEY_IM				=293	--(unused)
EFFECT_REVERSE_DECK					=294	--(unused)
EFFECT_REMOVE_BRAINWASHING			=295	--(unused)
EFFECT_BP_TWICE						=296	--(unused)
EFFECT_UNIQUE_CHECK					=297	--(unused)
EFFECT_MATCH_KILL					=300	--(unused)
EFFECT_SYNCHRO_CHECK				=310	--(unused)
EFFECT_QP_ACT_IN_NTPHAND			=311	--(unused)
EFFECT_MUST_BE_MATERIAL				=312	--(unused, only available in YGOPro Percy)
EFFECT_TO_GRAVE_REDIRECT_CB			=313	--(unused)
EFFECT_CHANGE_LEVEL_FINAL			=314	--(unused, only available in YGOPro Percy)
EFFECT_CHANGE_RANK_FINAL			=315	--(unused, only available in YGOPro Percy)
EFFECT_MUST_BE_FMATERIAL			=316	--(unused, only available in YGOPro Percy)
EFFECT_MUST_BE_XMATERIAL			=317	--(unused, only available in YGOPro Percy)
EFFECT_MUST_BE_LMATERIAL			=318	--(unused, only available in YGOPro Percy)
EFFECT_SPSUMMON_PROC_G				=320	--(unused)
EFFECT_SPSUMMON_COUNT_LIMIT			=330	--(unused)
EFFECT_LEFT_SPSUMMON_COUNT			=331	--(unused)
EFFECT_CANNOT_SELECT_BATTLE_TARGET	=332	--Cannot target cards for attacks
EFFECT_CANNOT_SELECT_EFFECT_TARGET	=333	--(unused)
EFFECT_ADD_SETCODE					=334	--Add setname
EFFECT_ADD_CREATURE_RACE			=334	--Add race
EFFECT_NO_EFFECT_DAMAGE				=335	--(unused)
EFFECT_UNSUMMONABLE_CARD			=336	--(unused, only available in YGOPro Percy)
EFFECT_DISABLE_CHAIN_FIELD			=337	--(N/A)
EFFECT_DISCARD_COST_CHANGE			=338	--(unused)
EFFECT_HAND_SYNCHRO					=339	--(unused)
EFFECT_ADD_FUSION_CODE				=340	--(unused)
EFFECT_ADD_FUSION_SETCODE			=341	--(unused)
EFFECT_RISE_TO_FULL_HEIGHT			=342	--(unused, only available in YGOPro Percy)
EFFECT_ONLY_ATTACK_MONSTER			=343	--(unused)
EFFECT_MUST_ATTACK_CREATURE			=344	--Must attack X if able
EFFECT_PATRICIAN_OF_DARKNESS		=345	--(unused)
EFFECT_EXTRA_ATTACK_MONSTER			=346	--(unused)
EFFECT_UNION_STATUS					=347	--(unused)
EFFECT_OLDUNION_STATUS				=348	--(unused)
EFFECT_ADD_FUSION_ATTRIBUTE			=349	--(unused, reserved)
EFFECT_REMOVE_FUSION_ATTRIBUTE		=350	--(unused, reserved)
EFFECT_CHANGE_FUSION_ATTRIBUTE		=351	--(unused)
EFFECT_EXTRA_FUSION_MATERIAL		=352	--(unused)
EFFECT_TUNER_MATERIAL_LIMIT			=353	--(unused)
EFFECT_ADD_LINK_CODE				=354	--(unused)
EFFECT_ADD_LINK_SETCODE				=355	--(unused, reserved)
EFFECT_ADD_LINK_ATTRIBUTE			=356	--(unused, not available in YGOPro Percy)
EFFECT_ADD_LINK_RACE				=357	--(unused, not available in YGOPro Percy)
EFFECT_EXTRA_MATERIAL				=358	--(unused, only available in YGOPro Percy)
EFFECT_QP_ACT_IN_SET_TURN			=359	--(unused, not available in YGOPro Percy)
EFFECT_EXTRA_PENDULUM_SUMMON		=360	--(unused, not available in YGOPro Percy)
EFFECT_MATERIAL_LIMIT				=361	--(unused, not available in YGOPro Percy)
EFFECT_SET_BATTLE_ATTACK			=362	--(unused, not available in YGOPro Percy)
EFFECT_SET_BATTLE_DEFENSE			=363	--(unused, not available in YGOPro Percy)
--The following is only available in YGOPro Percy
EFFECT_CANNOT_LOSE_DECK				=400	--(unused)
EFFECT_CANNOT_LOSE_LP				=401	--(unused)
EFFECT_CANNOT_LOSE_EFFECT			=402	--(unused)
EFFECT_BP_FIRST_TURN				=403	--Can conduct the Battle Phase of the first turn
EFFECT_UNSTOPPABLE_ATTACK			=404	--(unused)
EFFECT_ALLOW_NEGATIVE				=405	--(unused)
EFFECT_SELF_ATTACK					=406	--(unused)
EFFECT_BECOME_QUICK					=407	--(unused)
EFFECT_LEVEL_RANK					=408	--(unused)
EFFECT_RANK_LEVEL					=409	--(unused)
EFFECT_LEVEL_RANK_S					=410	--(unused)
EFFECT_RANK_LEVEL_S					=411	--(unused)
EFFECT_UPDATE_LINK					=420	--(unused)
EFFECT_CHANGE_LINK					=421	--(unused)
EFFECT_CHANGE_LINK_FINAL			=422	--(unused)
EFFECT_ADD_LINKMARKER				=423	--(unused)
EFFECT_REMOVE_LINKMARKER			=424	--(unused)
EFFECT_CHANGE_LINKMARKER			=425	--(unused)
--The following is only available in YGOPro KJ
EFFECT_IGNORE_TAP					=500	--Workaround to not tap a creature at the end of the Damage Step
EFFECT_BROKEN_SHIELD				=501	--Register a broken shield
EFFECT_BLOCKED						=502	--Register a creature that has become blocked
EFFECT_BREAK_SHIELD					=503	--Register number of broken shields
EFFECT_BLOCKER						=600	--Blocker ("Frogzooka" 1TVR 2/43)
EFFECT_GUARD						=601	--Guard ("Frogzooka" 1TVR 2/43)
EFFECT_SHIELD_BLAST					=602	--Shield Blast ("Ice Blade" 1TVR 5/43)
EFFECT_BREAKER						=603	--Breaker ("Gigargon" 1TVR 16/43)
EFFECT_DOUBLE_BREAKER				=604	--Double Breaker ("Gigargon" 1TVR 16/43)
EFFECT_SLAYER						=605	--Slayer ("Skull Cutter" 1TVR 20/43)
EFFECT_FAST_ATTACK					=606	--Fast Attack ("Draglide the Swiftest" 1TVR 25/43)
EFFECT_ATTACK_UNTAPPED				=607	--Can attack untapped creatures ("Little Hissy" 1TVR 28/43)
EFFECT_POWERFUL_ATTACK				=608	--Powerful Attack ("Pyro Trooper" 1TVR 30/43)
EFFECT_TURN_ATTACK_TAPPED			=609	--Can attack tapped creatures on the turn it enters the battle zone ("Tatsurion" 1TVR S2/S2)
EFFECT_SKIRMISHER					=610	--Skirmisher ("Grand Gure, Tower Keeper" 2DED 2/55)
EFFECT_UNTAPPED_BE_ATTACKED			=611	--Can be attacked as though it were tapped (Chain-Lash Tatsurion" 2DED 35/55)
EFFECT_IGNORE_GUARD					=612	--Ignore "Guard" ("Rally the Reserves" 3RIS 20/165)
EFFECT_IGNORE_SKIRMISHER			=613	--Ignore "Skirmisher" ("Rally the Reserves" 3RIS 20/165)
EFFECT_CANNOT_BLOCK					=614	--Cannot block ("Scaradorable the Hunter" 3RIS 89/165, "Squillace Scourge" 7CLA S8/S10)
EFFECT_CANNOT_ATTACK_CREATURE		=615	--Cannot attack creatures ("Forsett, Heroic Shaman" 4EVO 46/55)
EFFECT_TRIPLE_BREAKER				=616	--Triple Breaker ("Evo Fury Tatsurion" 4EVO S4/S5)
EFFECT_DONOT_UNTAP_START_STEP		=617	--Does not untap at the start of the turn ("Lyra, the Blazing Sun" 6DSI 7/55)
EFFECT_TURN_ATTACK_UNTAPPED			=618	--Can attack untapped creatures on the turn it enters the battle zone ("Billion-Degree Dragon" P19/Y1PRM)
EFFECT_EVOLUTION_ANY_RACE			=619	--Can be evolved on as though it had all races ("Shapeshifter Scaradorable" 7CLA 36/110)
EFFECT_EVOLUTION_ANY_CODE			=620	--Can be evolved on as though it had all card names ("Shapeshifter Scaradorable" 7CLA 36/110)
EFFECT_EVOLUTION_ANY_CIVILIZATION	=621	--Can be evolved on as though it had all civilizations ("Shapeshifter Scaradorable" 7CLA 36/110)
EFFECT_WINS_ALL_BATTLES				=622	--Wins all its battles ("Ra-Vu the Indomitable" 9SHA 5/80)
EFFECT_ENTER_BZONE_TAPPED			=623	--Creature enters the battle zone tapped ("Wandering Brain-Eater" 10INV 21/80)
EFFECT_PROTECTOR					=624	--Protector ("Galsaur" 10INV 26/80)
EFFECT_BREAK_EXTRA_SHIELD			=625	--Breaks an additional shield ("Napalmeon the Conquering" 10INV S4/S10)
EFFECT_UNLEASH						=626	--Unleash ("Magistrate Jazuri" 13GAU 16/160)
EFFECT_POWERFUL_BLOCK				=627	--Powerful Block ("Steadfast Vorwhal" 13GAU 52/160)
EFFECT_CANNOT_TO_SZONE				=628	--Cannot be put into the shield zone ("Regent Sasha" 13GAU S2/S10)
EFFECT_VORTEX_EVOLUTION				=629	--Vortex Evolution ("Empyrean Overseer" 15VTX 9/160)
EFFECT_SUMMON_FOR_FREE				=630	--Player may summon a creature from their hand for free ("Aeronaut Glu-urrgle" 15VTX 31/160)
EFFECT_CANNOT_BREAK_SHIELD			=631	--Cannot break shields ("Cybertech Restraints" 16EYE 17/80)
EFFECT_TRAPPER						=632	--Trapper ("Essence Boar" 16EYE 56/80)
EFFECT_WORLD_BREAKER				=633	--World Breaker ("Ultimate Tatsurion" 16EYE S5/S5)
--Event Code
--Events that can be used as a trigger for Trigger Effects
EVENT_STARTUP					=1000	--(unused)
EVENT_FLIP						=1001	--(unused)
EVENT_FREE_CHAIN				=1002	--Open window to activate Ignition and Trigger Effects
EVENT_DESTROY					=1010	--(unused)
EVENT_TO_DPILE					=1011	--(unused)
EVENT_TO_MZONE_TAPPED			=1011	--When a card is put into the mana zone tapped
EVENT_TO_HAND					=1012	--(reserved) When a card is put into the hand
EVENT_TO_DECK					=1013	--(reserved) When a card is put into the deck
EVENT_TO_MZONE					=1014	--When a card is put into the mana zone
EVENT_LEAVE_BZONE				=1015	--When a creature leaves the battle zone (excluding being added to the shield zone)
EVENT_CHANGE_POS				=1016	--When a card position is changed
EVENT_RELEASE					=1017	--(unused)
EVENT_DISCARD					=1018	--When a card is discarded from the hand
EVENT_LEAVE_FIELD_P				=1019	--(unused)
EVENT_CHAIN_SOLVING				=1020	--(unused)
EVENT_CHAIN_ACTIVATING			=1021	--(unused)
EVENT_CHAIN_SOLVED				=1022	--After a Chain resolves
EVENT_CHAIN_ACTIVATED			=1023	--(N/A)
EVENT_CHAIN_NEGATED				=1024	--(unused)
EVENT_CHAIN_DISABLED			=1025	--(unused)
EVENT_CHAIN_END					=1026	--When a series of Chains has resolved
EVENT_CHAINING					=1027	--When a card/effect is activating in response to another card/effect
EVENT_BECOME_TARGET				=1028	--(unused)
EVENT_BANISHED					=1029	--When a creature is banished
EVENT_MOVE						=1030	--(unused, not available in YGOPro Percy)
EVENT_ADJUST					=1040	--After adjusting the adjust_all() card
EVENT_BREAK_EFFECT				=1050	--(unused, not available in YGOPro Percy)
EVENT_SUMMON_SUCCESS			=1100	--(unused)
EVENT_FLIP_SUMMON_SUCCESS		=1101	--(unused)
EVENT_COME_INTO_PLAY			=1102	--When a creature is put into the battle zone
EVENT_SUMMON					=1103	--(unused)
EVENT_FLIP_SUMMON				=1104	--(unused)
EVENT_SPSUMMON					=1105	--(unused)
EVENT_MSET						=1106	--(unused)
EVENT_SSET						=1107	--(unused)
EVENT_BE_MATERIAL				=1108	--(unused)
EVENT_BE_PRE_MATERIAL			=1109	--(unused)
EVENT_DRAW						=1110	--When a card is drawn
EVENT_DAMAGE					=1111	--(unused)
EVENT_RECOVER					=1112	--(unused)
EVENT_UNTAP_STEP				=1113	--Beginning Step (Untap Step)
EVENT_SUMMON_NEGATED			=1114	--(unused, not available in YGOPro Percy)
EVENT_FLIP_SUMMON_NEGATED		=1115	--(unused, not available in YGOPro Percy)
EVENT_SPSUMMON_NEGATED			=1116	--(unused, not available in YGOPro Percy)
EVENT_CONTROL_CHANGED			=1120	--(unused)
EVENT_EQUIP						=1121	--(unused)
EVENT_ATTACK_ANNOUNCE			=1130	--When a card declares an attack
EVENT_BE_BATTLE_TARGET			=1131	--When a card is targeted for an attack
EVENT_BATTLE_START				=1132	--At the start of a battle
EVENT_BATTLE_CONFIRM			=1133	--When a creature is attacking and is not blocked
EVENT_ATTACK_SHIELD				=1134	--Before an attacking creature breaks the opponent's shield
EVENT_DAMAGE_CALCULATING		=1135	--(N/A)
EVENT_PRE_BATTLE_DAMAGE			=1136	--When battle damage occurs (using EFFECT_TYPE_CONTINUOUS)
EVENT_BATTLE_END				=1137	--(N/A)
EVENT_BATTLED					=1138	--At the end of a battle
EVENT_BATTLE_BANISHING			=1139	--When a creature wins a battle
EVENT_BATTLE_BANISHED			=1140	--When a creature loses a battle
EVENT_ATTACK_END				=1141	--At the end of an attack
EVENT_ATTACK_DISABLED			=1142	--(unused)
EVENT_BATTLE_DAMAGE				=1143	--(unused)
EVENT_TOSS_DICE					=1150	--(unused)
EVENT_TOSS_COIN					=1151	--(unused)
EVENT_TOSS_COIN_NEGATE			=1152	--(unused)
EVENT_TOSS_DICE_NEGATE			=1153	--(unused)
EVENT_LEVEL_UP					=1200	--(unused)
EVENT_PAY_LPCOST				=1201	--(unused)
EVENT_DETACH_MATERIAL			=1202	--(unused)
EVENT_RETURN_TO_GRAVE			=1203	--(unused)
EVENT_TURN_END					=1210	--At the end of the turn
EVENT_PHASE						=0x1000	--During a phase of a turn (combined with PHASE constant)
EVENT_PHASE_START				=0x2000	--At the start of a phase of a turn (combined with PHASE constant)
EVENT_ADD_COUNTER				=0x10000	--(unused, combined with counter ID)
EVENT_REMOVE_COUNTER			=0x20000	--(unused, combined with counter ID)
EVENT_CUSTOM					=0x10000000	--Custom event
--The following is only available in YGOPro KJ
EVENT_TRIGGER_SHIELD_BLAST		=CARD_ICE_BLADE				--Trigger a card's "Shield Blast" ability
EVENT_WIN_BATTLE				=CARD_SKEETER_SWARMER		--When a creature wins a battle (used with EVENT_BATTLE_DESTROYING)
EVENT_BLOCK						=CARD_STAR_LANTERN			--When a creature blocks
EVENT_CAST_FREE					=CARD_BOTTLE_OF_WISHES		--Cast a spell for free
EVENT_LOSE_BATTLE				=CARD_KING_POSEIDON			--When a creature loses a battle (used with EVENT_BATTLE_BANISHED)
EVENT_EVOLUTION_TO_BZONE		=CARD_KHORDIA_SOUL_TYRANT	--When an evolution creature is put into the battle zone by effect
EVENT_BECOME_BLOCKED			=CARD_VECTRON_CRAWLER		--When a creature becomes blocked
EVENT_CLASH						=CARD_SPARK_OF_HUNGER		--When a player clashes with their opponent
--Effect Category
CATEGORY_BLOCKER				=0x1	--Blocker ("King Pontias" 1TVR 7/43)
CATEGORY_SHIELD_BLAST			=0x2	--Shield Blast ("Krotork the Mirror" 15VTX S8/S10)
--Hint
--Message displayed in the center of the screen
HINT_EVENT				=1	--(unused)
HINT_MESSAGE			=2	--Display a string
HINT_SELECTMSG			=3	--Display a selection message
HINT_OPSELECTED			=4	--Display the selected effect
HINT_EFFECT				=5	--(unused)
HINT_RACE				=6	--(unused)
HINT_ATTRIB				=7	--(unused)
HINT_CODE				=8	--(unused)
HINT_NUMBER				=9	--Display the numerical value selected by the effect
HINT_CARD				=10	--Display the card name selected by the effect
HINT_ZONE				=11	--(unused, not available in YGOPro Percy)
--Card Hint
--Message displayed in the white frame that appears when you place the cursor on the card
CHINT_TURN				=1	--(unused)
CHINT_CARD				=2	--(unused)
CHINT_RACE				=3	--(unused)
CHINT_ATTRIBUTE			=4	--(unused)
CHINT_NUMBER			=5	--(unused)
CHINT_DESC				=6	--(unused)
--Opcode
OPCODE_ADD				=0x40000000		--(unused)
OPCODE_SUB				=0x40000001		--(unused)
OPCODE_MUL				=0x40000002		--(unused)
OPCODE_DIV				=0x40000003		--(unused)
OPCODE_AND				=0x40000004		--(unused)
OPCODE_OR				=0x40000005		--(unused)
OPCODE_NEG				=0x40000006		--(unused)
OPCODE_NOT				=0x40000007		--(unused)
OPCODE_ISCODE			=0x40000100		--(unused)
OPCODE_ISSETCARD		=0x40000101		--(unused)
OPCODE_ISTYPE			=0x40000102		--(unused)
OPCODE_ISRACE			=0x40000103		--(unused)
OPCODE_ISATTRIBUTE		=0x40000104		--(unused)
--Damage
DOUBLE_DAMAGE			=0x80000000		--(unused, not available in YGOPro Percy)
HALF_DAMAGE				=0x80000001		--(unused, not available in YGOPro Percy)
--Hint Message
--Message displayed at the top of the screen
HINTMSG_TOMZONE			=500	--Choose a card to put into the mana zone.
HINTMSG_TAP				=501	--Choose a card to tap.
HINTMSG_BREAK			=502	--Choose a shield to break.
HINTMSG_ANNOUNCECHOOSE	=503	--Choose how many cards?
HINTMSG_RTOHAND			=504	--Choose a card to return to its owner's hand.
HINTMSG_ATOHAND			=505	--Choose a card to put into your hand.
HINTMSG_BANISH			=506	--Choose a card to banish.
HINTMSG_DISCARD			=507	--Choose a card to discard.
HINTMSG_TARGET			=508	--Choose a target for the ability.
HINTMSG_CREATURE		=509	--Choose a creature.
HINTMSG_UNTAP			=510	--Choose a card to untap.
HINTMSG_TODECK			=511	--Choose a card to return to its owner's deck.
HINTMSG_BANISHREPLACE	=512	--Choose another creature to be banished instead.
HINTMSG_EVOLVE			=513	--Choose a creature to evolve.
HINTMSG_CONFIRM			=514	--Choose a card to look at it.
HINTMSG_CASTFREE		=515	--Choose a spell to cast for free.
HINTMSG_TOSZONE			=516	--Choose a card to put into its owner's shield zone.
HINTMSG_TODECKBOT		=517	--Choose a card to put on the bottom of its owner's deck.
HINTMSG_TODECKTOP		=518	--Choose a card to put on top of its owner's deck.
HINTMSG_TOBZONE			=519	--Choose a creature to put into the battle zone.
HINTMSG_ANNOUNCEDRAW	=520	--Draw how many cards?
HINTMSG_TODPILE			=521	--Choose a card to put into the discard pile.
HINTMSG_ANNOUNCETOMZONE	=522	--Put how many into mana zone?
HINTMSG_ANNOUNCENAME	=523	--Name a card.
HINTMSG_ANNOUNCECOST	=524	--Choose a level.
HINTMSG_ANNOUNCEPOWER	=525	--Choose a power.
HINTMSG_CARD			=526	--Choose a card.
HINTMSG_APPLYABILITY	=556	--Choose an ability to apply.
--Information displayed in a dialog box
ERROR_NOBZONES			=1630	--You may have up to 5 creatures in the battle zone when playing with this app. However, there is no limit when playing the actual card game.
ERROR_NOSZONES			=1631	--You may have up to 5 shields when playing with this app. However, there is no limit when playing the actual card game.
ERROR_NOTARGETS			=1632	--There is no applicable card.
ERROR_NOSBLAST			=1633	--There is no "Shield Blast" ability that can be activated during this time.
--Yes No Message (for Duel.SelectYesNo)
YESNOMSG_CHOOSE			=600	--Choose a card?
YESNOMSG_DRAW			=601	--Draw a card?
YESNOMSG_TODECKBOT		=602	--Put a card on the bottom of your deck?
YESNOMSG_TOMZONE		=603	--Put a card into your mana zone?
YESNOMSG_TOHAND			=604	--Put a card into your hand?
YESNOMSG_TOSZONE		=605	--Put a card into your shield zone?
YESNOMSG_TODPILE		=606	--Put a card into your discard pile?
YESNOMSG_SUMMONFREE		=607	--Summon for free?
YESNOMSG_PLAYFREE		=608	--Play a card for free?
YESNOMSG_CLASH			=609	--Clash with your opponent?
--Option (for Duel.SelectOption)
OPTION_HEADS			=60		--(unused)
OPTION_TAILS			=61		--(unused)
--Description (for SetDescription, EFFECT_FLAG_CLIENT_HINT)
DESC_BROKEN				=300	--Broken shield
DESC_SUMMONSICKNESS		=301	--Summoning Sickness
DESC_CANNOTATTACK		=302	--Can't attack
DESC_SUMMON				=1152	--Summon
DESC_EVOLVE				=1170	--Evolve
DESC_BEGINNING_PHASE	=1650	--At the start of your turn, if you have any tapped cards, untap them.
DESC_MANA_PHASE			=1651	--Put 1 card from your hand into your mana zone. You can skip charging mana if you want.
DESC_LOSE_BATTLE		=1652	--Banish the creature(s) that lost the battle.
DESC_BLOCKED			=1653	--Your creature has been blocked!
DESC_WINCLASH			=1654	--You won the clash!
DESC_LOSECLASH			=1655	--You lost the clash!
DESC_BLOCKER			=1660	--Blocker (Whenever an opponent's creature attacks, you may tap this creature to stop the attack. Then the 2 creatures battle.)
DESC_SHIELD_BLAST_S		=1661	--(reserved) Shield Blast (Instead of putting this spell into your hand from a broken shield, you may cast it for free.)
DESC_SLAYER				=1662	--Slayer (When this creature loses a battle, banish the other creature.)
DESC_PROTECTOR			=1663	--Protector (You may tap this creature to change an attack on one of your other creatures to this creature.)
DESC_SHIELD_BLAST_C		=1664	--Shield Blast (Instead of putting this creature into your hand from a broken shield, you may summon it for free.)
DESC_TRAPPER			=1665	--Trapper (When a creature wins a battle against this creature, put that creature into your opponent's mana zone.)
DESC_NON_BREAKER		=1800	--(reserved) This creature breaks 1 shield.
DESC_DOUBLE_BREAKER		=1801	--Double Breaker (This creature breaks 2 shields.)
DESC_TRIPLE_BREAKER		=1802	--Triple Breaker (This creature breaks 3 shields.)
DESC_WORLD_BREAKER		=1803	--World Breaker (This creature breaks all your opponent's shields.)
--Timing
--Free Chain activation timing
TIMING_DRAW_PHASE			=0x1			--(unused)
TIMING_STANDBY_PHASE		=0x2			--(unused)
TIMING_MAIN_END				=0x4			--(unused)
TIMING_BATTLE_START			=0x8			--Start of Battle Phase
TIMING_BATTLE_END			=0x10			--End of Battle Phase
TIMING_END_PHASE			=0x20			--(unused)
TIMING_SUMMON				=0x40			--(unused)
TIMING_SPSUMMON				=0x80			--(unused)
TIMING_FLIPSUMMON			=0x100			--(unused)
TIMING_MSET					=0x200			--(unused)
TIMING_SSET					=0x400			--(unused)
TIMING_POS_CHANGE			=0x800			--(unused)
TIMING_ATTACK				=0x1000			--(unused)
TIMING_DAMAGE_STEP			=0x2000			--(unused)
TIMING_DAMAGE_CAL			=0x4000			--(unused)
TIMING_CHAIN_END			=0x8000			--(unused)
TIMING_DRAW					=0x10000		--(unused)
TIMING_DAMAGE				=0x20000		--(unused)
TIMING_RECOVER				=0x40000		--(unused)
TIMING_DESTROY				=0x80000		--(unused)
TIMING_REMOVE				=0x100000		--(unused)
TIMING_TOHAND				=0x200000		--(unused)
TIMING_TODECK				=0x400000		--(unused)
TIMING_TOGRAVE				=0x800000		--(unused)
TIMING_BATTLE_PHASE			=0x1000000		--Battle Phase
TIMING_EQUIP				=0x2000000		--(unused)
TIMING_BATTLE_STEP_END		=0x4000000		--End of Battle Step
--Timing combinations
TIMINGS_CHECK_MONSTER		=0x1c0			--(unused) TIMING_SUMMON+TIMING_SPSUMMON+TIMING_FLIPSUMMON
--Global Flag
--Special effect flag
GLOBALFLAG_DECK_REVERSE_CHECK	=0x1		--(unused)
GLOBALFLAG_BRAINWASHING_CHECK	=0x2		--(unused)
GLOBALFLAG_SCRAP_CHIMERA		=0x4		--(unused)
GLOBALFLAG_DELAYED_QUICKEFFECT	=0x8		--(N/A)
GLOBALFLAG_DETACH_EVENT			=0x10		--(unused)
GLOBALFLAG_MUST_BE_SMATERIAL	=0x20		--(unused)
GLOBALFLAG_SPSUMMON_COUNT		=0x40		--(unused)
GLOBALFLAG_XMAT_COUNT_LIMIT		=0x80		--(unused)
GLOBALFLAG_SELF_TOGRAVE			=0x100		--(unused)
GLOBALFLAG_SPSUMMON_ONCE		=0x200		--(unused)
GLOBALFLAG_TUNE_MAGICIAN		=0x400		--(unused)
--Effect Count Code
--Limit the number of effects that can be used
EFFECT_COUNT_CODE_OATH			=0x10000000	--(unused)
EFFECT_COUNT_CODE_DUEL			=0x20000000	--(unused)
EFFECT_COUNT_CODE_SINGLE		=0x1		--(unused)
--Duel Options
DUEL_TEST_MODE			=0x01	--Test mode (not currently available)
DUEL_ATTACK_FIRST_TURN	=0x02	--Can attack during the first turn (for puzzles)
DUEL_NO_CHAIN_HINT		=0x04	--(N/A)
DUEL_OBSOLETE_RULING	=0x08	--Use old rules
DUEL_PSEUDO_SHUFFLE		=0x10	--Do not shuffle Deck
DUEL_TAG_MODE			=0x20	--2v2
DUEL_SIMPLE_AI			=0x40	--Semi-automatic AI (for puzzles)
SPEED_DUEL				=0x80	--Speed Duel (only available in YGOPro Percy)
--Activity Counter
--global: 1-6 (binary: 5,6)
--custom: 1-5,7 (binary: 1-5)
ACTIVITY_SUMMON			=1		--(unused)
ACTIVITY_NORMALSUMMON	=2		--(unused)
ACTIVITY_SPSUMMON		=3		--(unused)
ACTIVITY_FLIPSUMMON		=4		--(unused)
ACTIVITY_ATTACK			=5		--(unused)
ACTIVITY_BATTLE_PHASE	=6		--(unused, not available in Duel.AddCustomActivityCounter)
ACTIVITY_CHAIN			=7		--(unused, only available in Duel.AddCustomActivityCounter)
--Announce Type
ANNOUNCE_CARD			=0x7	--(unused, only available in YGOPro Percy)
ANNOUNCE_CARD_FILTER	=0x8	--(unused, only available in YGOPro Percy)
